# Generated by Django 3.2.9 on 2022-05-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('native_django', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(help_text='年龄不能<0  ', verbose_name='年龄'),
        ),
    ]
